# Site settings
title: XRP Canada
author:
  name: Glen Smith
  email: glensmithmail@yahoo.ca
description: "Crypto and Code."

# Build settings
remote_theme: broccolini/swiss

theme_color: red



baseurl: "blog" # the subpath of your site, e.g. /blog
url: "https://rockandrollcanada.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: blog
github_username: rockandrollcanada

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: glenrockinsmith
