# Site settings
title: XRP Canada
author:
  name: Glen Smith
  email: glensmithmail@yahoo.ca
description: "Crypto and Code."

# Build settings
remote_theme: broccolini/swiss

theme_color: red

